flowchart LR
    user(("User"))
    subgraph pytm ["Python Tool Manager"]
        direction TB
        database[("Code")]
        api[API]
        subgraph docker ["Docker"]
            subgraph tool ["Tool"]
            end
        end
    end
    subgraph lms ["Moodle"]
        direction TB
        subgraph exercise ["Exercise"]
        end
    end
    user <-- "Data" --> exercise
    exercise <-- "Data" --> api
    api <-- "Data" --> tool
    database --> tool
    api -- "Grades" --> lms